<h1>Сайты</h1>

<!-- TODO: remove this flash message out to /urls/{id} page -->
<?php if (!empty($params['flash'])): ?>
<p style="color: green"><?= $flash['success'][0]?></p>
<?php endif; ?>

<?php if (empty($urls)): ?>
<p>Нет добавленных url сайтов.</p>
<?php endif; ?>

<table class="table table-hover table-sm  table-bordered w-100" data-test="urls">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Имя</th>
      <th scope="col">Последнаяя проверка</th>
      <th scope="col">Код ответа</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($urls as $url): ?>
      <tr>
        <td><?= $url->getId() ?></td>
        <td><a href="/urls/<?= $url->getId() ?>"><?= htmlspecialchars($url->getName()) ?></a></td>
        <td></td>
        <td></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>


  
